repos:
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0  # Use the ref you want to point at
    hooks:
      - id: gradle-spotless
        args: ['-w', --wrapper]
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict